/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-container": "#005b14",
        "on-primary-fixed": "#001f24",
        "on-primary-container": "#002f35",
        "on-tertiary": "#562000",
        "secondary": "#88d982",
        "on-tertiary-fixed": "#341100",
        "surface-container-low": "#1c1b1b",
        "primary": "#00daf3",
        "error": "#ffb4ab",
        "inverse-primary": "#006875",
        "tertiary-container": "#f06600",
        "on-surface-variant": "#c1c6d7",
        "on-secondary-fixed": "#002204",
        "primary-fixed": "#9cf0ff",
        "on-tertiary-fixed-variant": "#7a3000",
        "surface-dim": "#131313",
        "secondary-fixed-dim": "#88d982",
        "primary-container": "#009fb2",
        "surface-container-high": "#2a2a2a",
        "surface-tint": "#00daf3",
        "on-secondary": "#003909",
        "surface-container-highest": "#353534",
        "inverse-surface": "#e5e2e1",
        "error-container": "#93000a",
        "surface-container": "#201f1f",
        "on-tertiary-container": "#4b1b00",
        "secondary-fixed": "#a3f69c",
        "surface": "#131313",
        "outline-variant": "#414754",
        "surface-container-lowest": "#0e0e0e",
        "on-surface": "#e5e2e1",
        "background": "#131313",
        "on-primary-fixed-variant": "#004f58",
        "on-background": "#e5e2e1",
        "on-secondary-container": "#81d27c",
        "inverse-on-surface": "#313030",
        "primary-fixed-dim": "#00daf3",
        "tertiary-fixed": "#ffdbcb",
        "on-error": "#690005",
        "outline": "#8b90a0",
        "tertiary-fixed-dim": "#ffb692",
        "surface-variant": "#353534",
        "on-primary": "#00363d",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#005312",
        "surface-bright": "#393939",
        "tertiary": "#ffb692"
      },
      fontFamily: {
        "headline": ["Lexend", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Space Grotesk", "sans-serif"]
      },
      borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
    },
  },
  plugins: [],
}
